import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Home,Users,Grid2X2,MessageCircle,User,Plus,Heart,Send,Shield,LogIn}from'lucide-react';
import'./style.css';

const API=localStorage.getItem('yunyu_api')||import.meta.env.VITE_API_BASE||'http://localhost:3000';
async function api(path,opt={}){
 const token=localStorage.getItem('yunyu_token');
 const headers={...(opt.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(opt.headers||{})};
 if(token)headers.Authorization='Bearer '+token;
 const r=await fetch(API+path,{...opt,headers});
 const d=await r.json().catch(()=>({}));
 if(!r.ok)throw new Error(d.message||d.error||'请求失败');
 return d.data??d;
}
const list=d=>Array.isArray(d)?d:(d?.posts||d?.apps||d?.messages||d?.items||d?.users||[]);
function Empty({title='暂无内容',desc='这里暂时还没有新的内容。'}){return <div className="empty"><div>☁️</div><b>{title}</b><p>{desc}</p></div>}
function Loading(){return <div className="loading">正在加载云屿…</div>}
function Modal({children,onClose}){return <div className="modal" onClick={onClose}><div className="modalbox" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button>{children}</div></div>}
function Auth({onClose,onDone}){const[mode,setMode]=useState('login'),[username,setU]=useState(''),[password,setP]=useState(''),[msg,setMsg]=useState('');async function go(){try{const d=await api('/auth/'+mode,{method:'POST',body:JSON.stringify({username,password})});if(d.token)localStorage.setItem('yunyu_token',d.token);if(mode==='login'){await onDone();onClose()}else{setMsg('注册成功，请登录');setMode('login')}}catch(e){setMsg(e.message)}}return <Modal onClose={onClose}><h2>{mode==='login'?'登录云屿':'注册云屿'}</h2><input value={username} onChange={e=>setU(e.target.value)} placeholder="用户名"/><input type="password" value={password} onChange={e=>setP(e.target.value)} placeholder="密码"/><button className="primary" onClick={go}>{mode==='login'?'登录':'注册'}</button><p className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'没有账号？注册':'已有账号？登录'}</p>{msg&&<p>{msg}</p>}</Modal>}
function Feed({community,openPost}){const[data,setData]=useState([]),[err,setErr]=useState('');useEffect(()=>{api('/posts').then(x=>setData(list(x))).catch(e=>setErr(e.message))},[]);return <><div className="hero"><small>YUNYU COMMUNITY · 4.2.8 WEB</small><h1>{community?'云屿社区':'云屿'}</h1><p>{community?'发现同频的人，也留下属于你的故事。':'欢迎来到属于每一个人的云端岛屿。'}</p></div>{err&&<div className="notice">{err}</div>}{!data.length&&!err&&<Empty title="还没有帖子" desc="成为第一个留下故事的人吧。"/>}{data.map(p=><article className="card clickable" key={p.id} onClick={()=>openPost(p)}><div className="row"><b>{p.title||'云屿帖子'}</b><span>Lv.{p.user_level||1}</span></div><p>{p.content}</p><div className="meta"><Heart size={14}/> {p.like_count||0} · 💬 {p.comment_count||0}</div></article>)}</>}
function Post({post,onClose}){const[p,setP]=useState(post),[comments,setC]=useState([]),[content,setText]=useState('');const load=()=>api('/posts/'+p.id+'/comments').then(x=>setC(list(x))).catch(()=>{});useEffect(()=>{api('/posts/'+p.id).then(setP).catch(()=>{});load()},[p.id]);return <Modal onClose={onClose}><h2>{p.title}</h2><p>{p.content}</p><button onClick={async()=>{try{await api('/posts/'+p.id+'/like',{method:'POST'});setP({...p,like_count:(p.like_count||0)+1})}catch(e){alert(e.message)}}}>❤️ 点赞 {p.like_count||0}</button><hr/>{comments.map(c=><div className="comment" key={c.id}><b>{c.display_name||c.username||'云屿用户'}</b><p>{c.content}</p></div>)}<div className="composer"><input value={content} onChange={e=>setText(e.target.value)} placeholder="写下你的评论"/><button onClick={async()=>{try{await api('/posts/'+p.id+'/comments',{method:'POST',body:JSON.stringify({content})});setText('');load()}catch(e){alert(e.message)}}}><Send/></button></div></Modal>}
function Publish({onClose}){const[title,setTitle]=useState(''),[content,setContent]=useState('');return <Modal onClose={onClose}><h2>发布帖子</h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="标题"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="分享此刻的想法…"/><button className="primary" onClick={async()=>{try{await api('/posts',{method:'POST',body:JSON.stringify({title,content})});onClose();location.reload()}catch(e){alert(e.message)}}}>发布</button></Modal>}
function Apps({openApp}){const[data,setData]=useState([]);useEffect(()=>{api('/apps').then(x=>setData(list(x))).catch(()=>{})},[]);return <><div className="row"><h1>应用中心</h1></div><div className="grid">{!data.length&&<Empty title="暂无应用" desc="应用中心正在等待新的作品。"/>}{data.map(a=><article className="card clickable" key={a.id} onClick={()=>openApp(a)}><b>{a.name}</b><p>{a.description}</p><div className="meta">⬇ {a.download_count||0}</div></article>)}</div></>}
function AppDetail({app,onClose}){const[a,setA]=useState(app);useEffect(()=>{api('/apps/'+app.id).then(setA).catch(()=>{})},[app.id]);return <Modal onClose={onClose}><h2>{a.name}</h2><p>{a.description||'暂无介绍'}</p><button className="primary" onClick={async()=>{try{await api('/apps/'+a.id+'/download',{method:'POST'});alert('下载记录成功')}catch(e){alert(e.message)}}}>下载 / 获取</button><button onClick={async()=>{try{await api('/apps/'+a.id+'/favorite',{method:'POST'});alert('已收藏')}catch(e){alert(e.message)}}}>收藏</button></Modal>}
function Messages({openChat}){const[data,setData]=useState([]);useEffect(()=>{api('/messages').then(x=>setData(list(x))).catch(()=>{})},[]);return <><h1>消息</h1>{!data.length&&<Empty title="暂时没有消息" desc="有新的互动时会出现在这里。"/>}{data.map(m=><div className="card clickable" key={m.id} onClick={()=>openChat(m)}><b>{m.display_name||m.username||'云屿用户'}</b><p>{m.last_content||m.content}</p></div>)}</>}
function Chat({chat,onClose}){const id=chat.user_id||chat.sender_id||chat.id,[data,setData]=useState([]),[content,setContent]=useState('');const load=()=>api('/messages/'+id).then(x=>setData(list(x))).catch(()=>{});useEffect(load,[id]);return <Modal onClose={onClose}><h2>{chat.display_name||chat.username||'聊天'}</h2><div className="chatbox">{data.map((m,i)=><div className="bubble" key={m.id||i}>{m.content}</div>)}</div><div className="composer"><input value={content} onChange={e=>setContent(e.target.value)} placeholder="输入消息…"/><button onClick={async()=>{try{await api('/messages/'+id,{method:'POST',body:JSON.stringify({content})});setContent('');load()}catch(e){alert(e.message)}}}><Send/></button></div></Modal>}
function Profile({me,openAuth,refresh}){
const[panel,setPanel]=useState(null),[favorites,setFav]=useState([]);
const[dark,setDark]=useState(localStorage.getItem('yunyu_theme')==='dark');
useEffect(()=>document.body.classList.toggle('dark',dark),[dark]);
function toggleTheme(){const v=!dark;setDark(v);localStorage.setItem('yunyu_theme',v?'dark':'light')}
if(!me)return <div className="card center"><User size={40}/><h2>登录后开启你的云屿</h2><button className="primary" onClick={openAuth}>登录 / 注册</button></div>;return <><h1>我的</h1><div className="level-card"><div><small>云屿等级</small><h2>Lv.{me.level||1}</h2></div><div><b>{me.exp||me.experience||0} EXP</b><p>{me.role||me.title||'云屿居民'}</p></div></div><div className="card"><h2>{me.display_name||me.username}</h2><p>{me.bio||'欢迎来到云屿'}</p></div><button className="card wide" onClick={async()=>{try{await api('/checkin',{method:'POST'});alert('签到成功');refresh()}catch(e){alert(e.message)}}}>每日签到</button><button className="card wide" onClick={toggleTheme}>{dark?'切换浅色模式':'切换深色模式'}</button><button className="card wide" onClick={async()=>{try{setFav(list(await api('/my/favorites')));setPanel('fav')}catch(e){alert(e.message)}}}>我的收藏</button><button className="card wide" onClick={()=>{const v=prompt('后端地址',API);if(v){localStorage.setItem('yunyu_api',v);location.reload()}}}>后端连接设置</button><button className="card wide danger" onClick={()=>{localStorage.removeItem('yunyu_token');location.reload()}}>退出登录</button>{panel==='fav'&&<Modal onClose={()=>setPanel(null)}><h2>我的收藏</h2>{favorites.map(x=><div className="card" key={x.id}><b>{x.name||x.title}</b><p>{x.description||x.content}</p></div>)}</Modal>}</>}
function Admin(){const[tab,setTab]=useState('统计'),[data,setData]=useState(null);const paths={'统计':'/admin/stats','用户':'/admin/users','帖子审核':'/admin/posts/pending','应用审核':'/admin/apps/pending','举报':'/admin/reports','公告':'/announcements'};useEffect(()=>{api(paths[tab]).then(setData).catch(e=>setData({message:e.message}))},[tab]);return <><h1>管理后台</h1><div className="admin-tabs">{Object.keys(paths).map(t=><button className={tab===t?'on':''} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="card"><pre>{JSON.stringify(data,null,2)}</pre></div></>}
function App(){const[tab,setTab]=useState(0),[auth,setAuth]=useState(false),[me,setMe]=useState(null),[detail,setDetail]=useState(null),[publish,setPublish]=useState(false);const refresh=async()=>{try{setMe(await api('/me'))}catch{setMe(null)}};useEffect(()=>{refresh()},[]);const pages=[<Feed openPost={setDetail}/>,<Feed community openPost={setDetail}/>,<Apps openApp={setDetail}/>,<Messages openChat={setDetail}/>,<Profile me={me} openAuth={()=>setAuth(true)} refresh={refresh}/>,<Admin/>];const tabs=[['首页',Home],['社区',Users],['应用',Grid2X2],['消息',MessageCircle],['我的',User]];return <div className="shell"><header><div><b>云屿</b><span>发现属于你的每一座云屿</span></div><div className="online-dot">Web 4.2.8</div>{me?<span>{me.display_name||me.username}</span>:<button onClick={()=>setAuth(true)}><LogIn/></button>}</header><main>{pages[tab]}</main>{tab<5&&<button className="fab" onClick={()=>setPublish(true)}><Plus/></button>}<nav>{tabs.map(([n,I],i)=><button className={tab===i?'active':''} onClick={()=>setTab(i)} key={n}><I size={20}/><span>{n}</span></button>)}<button className={tab===5?'active':''} onClick={()=>me?setTab(5):setAuth(true)}><Shield size={20}/><span>后台</span></button></nav>{auth&&<Auth onClose={()=>setAuth(false)} onDone={refresh}/>} {publish&&<Publish onClose={()=>setPublish(false)}/>} {detail&&((detail.last_content!==undefined||detail.user_id||detail.sender_id)?<Chat chat={detail} onClose={()=>setDetail(null)}/>:detail.name?<AppDetail app={detail} onClose={()=>setDetail(null)}/>:<Post post={detail} onClose={()=>setDetail(null)}/>)}</div>}
createRoot(document.getElementById('root')).render(<App/>);
