// 云屿前端 API 集合（与后端路由一一对应）
import { get, post, put, del } from './request'

export const api = {
  // ===== 账号 =====
  sendCode: (email, purpose) => post('/api/auth/send-code', { email, purpose }),
  verifyCode: (email, purpose, code) => post('/api/auth/verify-code', { email, purpose, code }),
  register: (body) => post('/api/auth/register', body),
  login: (email, password) => post('/api/auth/login', { email, password }),
  resetPassword: (body) => post('/api/auth/reset-password', body),
  changePassword: (body) => post('/api/auth/change-password', body),
  changeEmail: (body) => post('/api/auth/change-email', body),

  // ===== 首页 & 公共 =====
  home: () => get('/api/home'),
  announcements: () => get('/api/announcements'),
  announcementDetail: (id) => get(`/api/announcements/${id}`),
  search: (kw) => get('/api/search?kw=' + encodeURIComponent(kw)),
  hotSearch: () => get('/api/search/hot'),
  searchHistory: () => get('/api/search/history'),
  clearSearchHistory: () => del('/api/search/history'),
  about: () => get('/api/about'),

  // ===== 软件 =====
  softwareList: (params = '') => get('/api/software' + params),
  softwareDetail: (id) => get(`/api/software/${id}`),
  softwareCategories: () => get('/api/software/categories'),
  softwareCollections: () => get('/api/software/collections'),
  softwareCollectionDetail: (id) => get(`/api/software/collections/${id}`),
  softwareDownload: (id) => post(`/api/software/${id}/download`),
  softwareFavorite: (id) => post(`/api/software/${id}/favorite`, {}),
  softwareUnfavorite: (id) => del(`/api/software/${id}/favorite`),
  softwareReport: (id, body) => post(`/api/software/${id}/report`, body),
  softwareRating: (id, body) => post(`/api/software/${id}/rating`, body),
  softwareRatings: (id) => get(`/api/software/${id}/ratings`),
  upload: (data) => post('/api/upload', { data }),
  trackEvent: (body) => post('/api/events/track', body),

  // ===== 帖子 =====
  posts: (params = '') => get('/api/posts' + params),
  postDetail: (id) => get(`/api/posts/${id}`),
  postCreate: (body) => post('/api/posts', body),
  postUpdate: (id, body) => put(`/api/posts/${id}`, body),
  postDelete: (id) => del(`/api/posts/${id}`),
  postLike: (id) => post(`/api/posts/${id}/like`, {}),
  postUnlike: (id) => del(`/api/posts/${id}/like`),
  postFavorite: (id) => post(`/api/posts/${id}/favorite`, {}),
  postUnfavorite: (id) => del(`/api/posts/${id}/favorite`),
  postComments: (id, params = '') => get(`/api/posts/${id}/comments` + params),
  postComment: (id, body) => post(`/api/posts/${id}/comments`, body),
  commentLike: (id) => post(`/api/posts/comments/${id}/like`, {}),
  commentUnlike: (id) => del(`/api/posts/comments/${id}/like`),
  commentDelete: (id) => del(`/api/posts/comments/${id}`),
  postReport: (id, body) => post(`/api/posts/${id}/report`, body),
  topics: () => get('/api/posts/topics'),
  hotUsers: () => get('/api/posts/hot-users'),

  // ===== 用户 =====
  me: () => get('/api/users/me'),
  userProfile: (id) => get(`/api/users/${id}`),
  updateProfile: (body) => put('/api/users/profile', body),
  myPosts: (params = '') => get('/api/users/me/posts' + params),
  myComments: (params = '') => get('/api/users/me/comments' + params),
  myFavorites: (params = '') => get('/api/users/me/favorites' + params),
  myFollowing: (params = '') => get('/api/users/me/following' + params),
  myFollowers: (params = '') => get('/api/users/me/followers' + params),
  myCollections: () => get('/api/users/me/collections'),
  collectionCreate: (body) => post('/api/users/me/collections', body),
  collectionUpdate: (id, body) => put(`/api/users/me/collections/${id}`, body),
  collectionDelete: (id) => del(`/api/users/me/collections/${id}`),
  collectionDetail: (id) => get(`/api/users/collections/${id}`),
  collectionGallary: (params = '') => get('/api/users/collections' + params),
  collectionFollow: (id) => post(`/api/users/me/collections/${id}/follow`, {}),
  collectionUnfollow: (id) => del(`/api/users/me/collections/${id}/follow`),
  followedCollections: () => get('/api/users/me/followed-collections'),
  follow: (id) => post(`/api/users/follow/${id}`, {}),
  unfollow: (id) => del(`/api/users/follow/${id}`),
  checkin: () => post('/api/users/checkin', {}),
  checkinStatus: () => get('/api/users/checkin/status'),
  levels: () => get('/api/users/levels'),
  tasks: () => get('/api/users/tasks'),
  claimTask: (id) => post(`/api/users/tasks/${id}/claim`, {}),
  notifications: (params = '') => get('/api/users/notifications' + params),
  notificationRead: (id) => post('/api/users/notifications/read', { id }),
  notificationReadAll: () => post('/api/users/notifications/read-all', {}),
  conversations: () => get('/api/users/conversations'),
  messages: (userId, params = '') => get(`/api/users/messages/${userId}` + params),
  sendMessage: (body) => post('/api/users/messages', body),
  unreadSummary: () => get('/api/users/unread-summary'),

  // ===== 管理后台 =====
  admin: {
    me: () => get('/api/admin/me'),
    dashboard: () => get('/api/admin/dashboard'),
    users: (params = '') => get('/api/admin/users' + params),
    userDetail: (id) => get(`/api/admin/users/${id}`),
    userStatus: (id, status) => put(`/api/admin/users/${id}/status`, { status }),
    userExp: (id, body) => put(`/api/admin/users/${id}/exp`, body),
    userRole: (id, body) => put(`/api/admin/users/${id}/role`, body),
    posts: (params = '') => get('/api/admin/posts' + params),
    postState: (id, field, value) => put(`/api/admin/posts/${id}/state`, { field, value }),
    postUpdate: (id, body) => put(`/api/admin/posts/${id}`, body),
    postDelete: (id) => del(`/api/admin/posts/${id}`),
    comments: (params = '') => get('/api/admin/comments' + params),
    commentDelete: (id) => del(`/api/admin/comments/${id}`),
    topics: () => get('/api/admin/topics'),
    topicCreate: (body) => post('/api/admin/topics', body),
    topicUpdate: (id, body) => put(`/api/admin/topics/${id}`, body),
    topicDelete: (id) => del(`/api/admin/topics/${id}`),
    software: (params = '') => get('/api/admin/software' + params),
    softwareDetail: (id) => get(`/api/admin/software/${id}`),
    softwareCreate: (body) => post('/api/admin/software', body),
    softwareUpdate: (id, body) => put(`/api/admin/software/${id}`, body),
    softwareDelete: (id) => del(`/api/admin/software/${id}`),
    softwareVersions: (id) => get(`/api/admin/software/${id}/versions`),
    softwareVersionCreate: (id, body) => post(`/api/admin/software/${id}/versions`, body),
    softwareVersionDelete: (id) => del(`/api/admin/software/versions/${id}`),
    categories: () => get('/api/admin/categories'),
    categoryCreate: (body) => post('/api/admin/categories', body),
    categoryUpdate: (id, body) => put(`/api/admin/categories/${id}`, body),
    categoryDelete: (id) => del(`/api/admin/categories/${id}`),
    collections: () => get('/api/admin/collections'),
    collectionCreate: (body) => post('/api/admin/collections', body),
    collectionUpdate: (id, body) => put(`/api/admin/collections/${id}`, body),
    collectionDelete: (id) => del(`/api/admin/collections/${id}`),
    userCollections: (params = '') => get('/api/admin/u-collections' + params),
    userCollectionDelete: (id) => del(`/api/admin/u-collections/${id}`),
    reports: (params = '') => get('/api/admin/reports' + params),
    reportHandle: (id, body) => put(`/api/admin/reports/${id}`, body),
    announcements: () => get('/api/admin/announcements'),
    announcementCreate: (body) => post('/api/admin/announcements', body),
    announcementUpdate: (id, body) => put(`/api/admin/announcements/${id}`, body),
    announcementDelete: (id) => del(`/api/admin/announcements/${id}`),
    checkins: () => get('/api/admin/checkins'),
    checkinRecords: (params = '') => get('/api/admin/checkins/records' + params),
    checkinReward: (day, body) => put(`/api/admin/checkin-rewards/${day}`, body),
    tasks: () => get('/api/admin/tasks'),
    taskCreate: (body) => post('/api/admin/tasks', body),
    taskUpdate: (id, body) => put(`/api/admin/tasks/${id}`, body),
    taskDelete: (id) => del(`/api/admin/tasks/${id}`),
    admins: () => get('/api/admin/admins'),
    adminCreate: (body) => post('/api/admin/admins', body),
    adminUpdate: (id, body) => put(`/api/admin/admins/${id}`, body),
    adminDelete: (id) => del(`/api/admin/admins/${id}`),
    roles: () => get('/api/admin/roles'),
    roleUpdate: (id, body) => put(`/api/admin/roles/${id}`, body),
    permissions: () => get('/api/admin/permissions'),
    emailConfig: () => get('/api/admin/email-config'),
    settings: () => get('/api/admin/settings'),
    settingsUpdate: (body) => put('/api/admin/settings', body),
    logs: (params = '') => get('/api/admin/logs' + params),
  }
}